server:
  port: 8761

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: smart-community-bean
  datasource:
    url: jdbc:mysql://localhost:3306/city?serverTimezone=Hongkong&useSSL=false&useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  session:
    store-type: none
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 39.100.124.150
    port: 6379
    database: 2




mybatis:
  typeAliasesPackage: com.liaoin.muti.test # com.artopcn.service.worker.siting.entity;
  mapperLocations: classpath*:repo/**/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
mapper:
  not-empty: true
  mappers: com.liaoin.muti.test.mybatis.BaseMapper
  identity: mysql
  before: true


swagger:
  enabled: true
  docket:
    userInfo:
      base-package: com.liaoin.muti.test.controller.user
      title: "用户基本信息"
    authMenu:
      base-package: com.liaoin.muti.test.controller.auth
      title: "权限-菜单"


config:
  registry:
    no-verify[0]: /swagger-**
    no-verify[1]: /images/**
    no-verify[2]: /webjars/**
    no-verify[3]: /v2/controller-docs**
    no-verify[4]: /swagger-resources/configuration/ui**
    no-verify[5]: /swagger-resources/configuration/security**
    no-verify[6]: /websocket/socketServer.ws**
    no-verify[7]: /sockjs/socketServer.ws**
    no-verify[8]: /doc.html
    no-verify[9]: /api-docs-ext
    no-verify[10]: /v2/api-docs
    no-verify[11]: /error
    no-verify[12]: /user/login

liaoin:
  security:
    o-auth2:
      clients[0]:
        clientId: user_1
        clientIdSecret: 123456
      clients[1]:
        clientId: user_2
        clientIdSecret: 12345
    browser:
      loginType: JSON
    default-login-processing-url-from: /authentication/form